import request from '../utils/request'

export const login = (data) => request.post('/auth/login', data)
export const register = (data) => request.post('/auth/register', data)
export const getUserInfo = () => request.get('/auth/info')
export const logout = () => request.post('/auth/logout')

export const getStudents = (params) => request.get('/students', { params })
export const getStudent = (id) => request.get(`/students/${id}`)
export const saveStudent = (data) => request.post('/students', data)
export const deleteStudent = (id) => request.delete(`/students/${id}`)
export const getInterestCourses = (id) => request.get(`/students/${id}/interest-courses`)
export const saveInterestCourses = (id, data) => request.post(`/students/${id}/interest-courses`, data)

export const getClasses = (params) => request.get('/classes', { params })
export const getAllClasses = () => request.get('/classes/all')
export const getClass = (id) => request.get(`/classes/${id}`)
export const saveClass = (data) => request.post('/classes', data)
export const deleteClass = (id) => request.delete(`/classes/${id}`)

export const getUniversities = (params) => request.get('/universities', { params })
export const getUniversity = (id) => request.get(`/universities/${id}`)
export const saveUniversity = (data) => request.post('/universities', data)
export const deleteUniversity = (id) => request.delete(`/universities/${id}`)
export const getDepartments = (universityId) => request.get(`/universities/${universityId}/departments`)
export const saveDepartment = (data) => request.post('/universities/departments', data)
export const deleteDepartment = (id) => request.delete(`/universities/departments/${id}`)
export const getMajors = (params) => request.get('/universities/majors', { params })
export const getMajor = (id) => request.get(`/universities/majors/${id}`)
export const saveMajor = (data) => request.post('/universities/majors', data)
export const deleteMajor = (id) => request.delete(`/universities/majors/${id}`)
export const getQuotas = (majorId) => request.get(`/universities/majors/${majorId}/quotas`)
export const saveQuota = (data) => request.post('/universities/majors/quotas', data)

export const getProvinces = () => request.get('/common/provinces')
export const getMajorCourses = (majorId) => request.get(`/common/majors/${majorId}/courses`)
export const saveMajorCourses = (majorId, data) => request.post(`/common/majors/${majorId}/courses`, data)

export const getProvincialScoreLines = (params) => request.get('/score-lines/provincial', { params })
export const saveProvincialScoreLine = (data) => request.post('/score-lines/provincial', data)
export const deleteProvincialScoreLine = (id) => request.delete(`/score-lines/provincial/${id}`)
export const getUniversityScoreLines = (params) => request.get('/score-lines/university', { params })
export const saveUniversityScoreLine = (data) => request.post('/score-lines/university', data)
export const deleteUniversityScoreLine = (id) => request.delete(`/score-lines/university/${id}`)

export const getApplications = (studentId) => request.get(`/applications/student/${studentId}`)
export const getApplicationWindow = () => request.get('/applications/window')
export const submitApplication = (data) => request.post('/applications/submit', data)
export const submitDraft = (studentId) => request.post(`/applications/student/${studentId}/submit-draft`)
export const getRecommend = (studentId) => request.get(`/applications/recommend/${studentId}`)
export const checkSubject = (studentId, majorId) => request.get('/applications/check-subject', { params: { studentId, majorId } })

export const executeAdmission = () => request.post('/admission/execute')
export const getAdmissionResults = (params) => request.get('/admission/results', { params })
export const getStudentResult = (studentId) => request.get(`/admission/student/${studentId}`)
export const getAdmissionLogs = () => request.get('/admission/logs')
export const getDashboard = () => request.get('/admission/dashboard')
