CREATE TABLE sys_user (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    username    VARCHAR(50)  NOT NULL UNIQUE,
    password    VARCHAR(100) NOT NULL,
    role        VARCHAR(20)  NOT NULL DEFAULT 'STUDENT',
    student_id  BIGINT,
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE province (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE class_info (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    grade       VARCHAR(20),
    teacher     VARCHAR(50),
    province_id BIGINT
);

CREATE TABLE student (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    student_no             VARCHAR(50) NOT NULL UNIQUE,
    name                   VARCHAR(50) NOT NULL,
    gender                 VARCHAR(10),
    id_card                VARCHAR(20),
    total_score            DECIMAL(6,2),
    chinese_score          DECIMAL(5,2),
    math_score             DECIMAL(5,2),
    foreign_language_score DECIMAL(5,2),
    province_id            BIGINT,
    class_id               BIGINT,
    subject_combo          VARCHAR(20),
    phone                  VARCHAR(20),
    status                 VARCHAR(20) DEFAULT 'ACTIVE'
);

CREATE TABLE university (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    name        VARCHAR(100) NOT NULL UNIQUE,
    type        VARCHAR(20),
    province_id BIGINT,
    batch       VARCHAR(20)
);

CREATE TABLE department (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    university_id BIGINT NOT NULL
);

CREATE TABLE major (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    department_id BIGINT NOT NULL,
    subject_req   VARCHAR(100),
    subject_type  VARCHAR(10),
    total_quota   INT DEFAULT 0
);

CREATE TABLE province_quota (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    major_id    BIGINT NOT NULL,
    province_id BIGINT NOT NULL,
    quota       INT DEFAULT 0,
    UNIQUE (major_id, province_id)
);

CREATE TABLE score_line (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    province_id  BIGINT NOT NULL,
    "year"       INT NOT NULL,
    batch        VARCHAR(20) NOT NULL,
    subject_type VARCHAR(10) NOT NULL,
    score        DECIMAL(6,2) NOT NULL,
    UNIQUE (province_id, "year", batch, subject_type)
);

CREATE TABLE university_score_line (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    university_id BIGINT NOT NULL,
    province_id   BIGINT NOT NULL,
    "year"        INT NOT NULL,
    major_id      BIGINT,
    min_score     DECIMAL(6,2),
    avg_score     DECIMAL(6,2),
    UNIQUE (university_id, province_id, "year", major_id)
);

CREATE TABLE interest_course (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    student_id BIGINT NOT NULL,
    name       VARCHAR(100) NOT NULL,
    UNIQUE (student_id, name)
);

CREATE TABLE major_course (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    major_id BIGINT NOT NULL,
    name     VARCHAR(100) NOT NULL,
    UNIQUE (major_id, name)
);

CREATE TABLE application (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    student_id    BIGINT NOT NULL,
    university_id BIGINT NOT NULL,
    priority      INT NOT NULL,
    accept_adjust BOOLEAN DEFAULT FALSE,
    status        VARCHAR(20) DEFAULT 'DRAFT',
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE application_major (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    application_id BIGINT NOT NULL,
    major_id       BIGINT NOT NULL,
    priority       INT NOT NULL
);

CREATE TABLE admission_result (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    student_id           BIGINT NOT NULL UNIQUE,
    university_id        BIGINT,
    major_id             BIGINT,
    status               VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    application_priority INT,
    is_adjusted          BOOLEAN DEFAULT FALSE,
    reason               VARCHAR(200)
);

CREATE TABLE admission_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    student_id    BIGINT NOT NULL,
    university_id BIGINT,
    major_id      BIGINT,
    action        VARCHAR(50) NOT NULL,
    detail        VARCHAR(500),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE sys_user
    ADD CONSTRAINT fk_sys_user_student FOREIGN KEY (student_id) REFERENCES student(id);
ALTER TABLE class_info
    ADD CONSTRAINT fk_class_info_province FOREIGN KEY (province_id) REFERENCES province(id);
ALTER TABLE student
    ADD CONSTRAINT fk_student_province FOREIGN KEY (province_id) REFERENCES province(id);
ALTER TABLE student
    ADD CONSTRAINT fk_student_class FOREIGN KEY (class_id) REFERENCES class_info(id);
ALTER TABLE university
    ADD CONSTRAINT fk_university_province FOREIGN KEY (province_id) REFERENCES province(id);
ALTER TABLE department
    ADD CONSTRAINT fk_department_university FOREIGN KEY (university_id) REFERENCES university(id) ON DELETE CASCADE;
ALTER TABLE major
    ADD CONSTRAINT fk_major_department FOREIGN KEY (department_id) REFERENCES department(id) ON DELETE CASCADE;
ALTER TABLE province_quota
    ADD CONSTRAINT fk_province_quota_major FOREIGN KEY (major_id) REFERENCES major(id) ON DELETE CASCADE;
ALTER TABLE province_quota
    ADD CONSTRAINT fk_province_quota_province FOREIGN KEY (province_id) REFERENCES province(id);
ALTER TABLE score_line
    ADD CONSTRAINT fk_score_line_province FOREIGN KEY (province_id) REFERENCES province(id);
ALTER TABLE university_score_line
    ADD CONSTRAINT fk_university_score_line_university FOREIGN KEY (university_id) REFERENCES university(id) ON DELETE CASCADE;
ALTER TABLE university_score_line
    ADD CONSTRAINT fk_university_score_line_province FOREIGN KEY (province_id) REFERENCES province(id);
ALTER TABLE university_score_line
    ADD CONSTRAINT fk_university_score_line_major FOREIGN KEY (major_id) REFERENCES major(id) ON DELETE CASCADE;
ALTER TABLE interest_course
    ADD CONSTRAINT fk_interest_course_student FOREIGN KEY (student_id) REFERENCES student(id) ON DELETE CASCADE;
ALTER TABLE major_course
    ADD CONSTRAINT fk_major_course_major FOREIGN KEY (major_id) REFERENCES major(id) ON DELETE CASCADE;
ALTER TABLE application
    ADD CONSTRAINT fk_application_student FOREIGN KEY (student_id) REFERENCES student(id) ON DELETE CASCADE;
ALTER TABLE application
    ADD CONSTRAINT fk_application_university FOREIGN KEY (university_id) REFERENCES university(id);
ALTER TABLE application_major
    ADD CONSTRAINT fk_application_major_application FOREIGN KEY (application_id) REFERENCES application(id) ON DELETE CASCADE;
ALTER TABLE application_major
    ADD CONSTRAINT fk_application_major_major FOREIGN KEY (major_id) REFERENCES major(id);
ALTER TABLE admission_result
    ADD CONSTRAINT fk_admission_result_student FOREIGN KEY (student_id) REFERENCES student(id) ON DELETE CASCADE;
ALTER TABLE admission_result
    ADD CONSTRAINT fk_admission_result_university FOREIGN KEY (university_id) REFERENCES university(id);
ALTER TABLE admission_result
    ADD CONSTRAINT fk_admission_result_major FOREIGN KEY (major_id) REFERENCES major(id);
ALTER TABLE admission_log
    ADD CONSTRAINT fk_admission_log_student FOREIGN KEY (student_id) REFERENCES student(id) ON DELETE CASCADE;

CREATE INDEX idx_student_score ON student(total_score DESC);
CREATE INDEX idx_student_class ON student(class_id);
CREATE INDEX idx_application_student_status_priority ON application(student_id, status, priority);
CREATE INDEX idx_application_major_application_priority ON application_major(application_id, priority);
CREATE INDEX idx_major_department ON major(department_id);
CREATE INDEX idx_province_quota_major_province ON province_quota(major_id, province_id);
CREATE INDEX idx_admission_result_query ON admission_result(status, university_id, student_id);
CREATE INDEX idx_admission_log_student ON admission_log(student_id);
