CREATE TABLE subject_category (
    code        VARCHAR(16) PRIMARY KEY,
    name        VARCHAR(16) NOT NULL UNIQUE,
    sort_order  SMALLINT NOT NULL UNIQUE,
    CONSTRAINT ck_subject_category_code CHECK (code IN ('PHYSICS', 'HISTORY'))
);

INSERT INTO subject_category(code, name, sort_order) VALUES
    ('PHYSICS', '物理类', 1),
    ('HISTORY', '历史类', 2);

CREATE TABLE subject_combination (
    code                VARCHAR(40) PRIMARY KEY,
    category_code       VARCHAR(16) NOT NULL,
    name                VARCHAR(40) NOT NULL UNIQUE,
    secondary_subject_1 VARCHAR(16) NOT NULL,
    secondary_subject_2 VARCHAR(16) NOT NULL,
    CONSTRAINT fk_subject_combination_category FOREIGN KEY (category_code)
        REFERENCES subject_category(code),
    CONSTRAINT uq_subject_combination_code_category UNIQUE (code, category_code),
    CONSTRAINT uq_subject_combination_subjects UNIQUE (
        category_code, secondary_subject_1, secondary_subject_2
    ),
    CONSTRAINT ck_subject_combination_secondary_1 CHECK (
        secondary_subject_1 IN ('CHEMISTRY', 'BIOLOGY', 'POLITICS', 'GEOGRAPHY')
    ),
    CONSTRAINT ck_subject_combination_secondary_2 CHECK (
        secondary_subject_2 IN ('CHEMISTRY', 'BIOLOGY', 'POLITICS', 'GEOGRAPHY')
    ),
    CONSTRAINT ck_subject_combination_distinct CHECK (secondary_subject_1 <> secondary_subject_2)
);

INSERT INTO subject_combination(
    code, category_code, name, secondary_subject_1, secondary_subject_2
) VALUES
    ('PHYSICS_CHEMISTRY_BIOLOGY', 'PHYSICS', '物理+化学+生物', 'CHEMISTRY', 'BIOLOGY'),
    ('PHYSICS_CHEMISTRY_POLITICS', 'PHYSICS', '物理+化学+政治', 'CHEMISTRY', 'POLITICS'),
    ('PHYSICS_CHEMISTRY_GEOGRAPHY', 'PHYSICS', '物理+化学+地理', 'CHEMISTRY', 'GEOGRAPHY'),
    ('PHYSICS_BIOLOGY_POLITICS', 'PHYSICS', '物理+生物+政治', 'BIOLOGY', 'POLITICS'),
    ('PHYSICS_BIOLOGY_GEOGRAPHY', 'PHYSICS', '物理+生物+地理', 'BIOLOGY', 'GEOGRAPHY'),
    ('PHYSICS_POLITICS_GEOGRAPHY', 'PHYSICS', '物理+政治+地理', 'POLITICS', 'GEOGRAPHY'),
    ('HISTORY_CHEMISTRY_BIOLOGY', 'HISTORY', '历史+化学+生物', 'CHEMISTRY', 'BIOLOGY'),
    ('HISTORY_CHEMISTRY_POLITICS', 'HISTORY', '历史+化学+政治', 'CHEMISTRY', 'POLITICS'),
    ('HISTORY_CHEMISTRY_GEOGRAPHY', 'HISTORY', '历史+化学+地理', 'CHEMISTRY', 'GEOGRAPHY'),
    ('HISTORY_BIOLOGY_POLITICS', 'HISTORY', '历史+生物+政治', 'BIOLOGY', 'POLITICS'),
    ('HISTORY_BIOLOGY_GEOGRAPHY', 'HISTORY', '历史+生物+地理', 'BIOLOGY', 'GEOGRAPHY'),
    ('HISTORY_POLITICS_GEOGRAPHY', 'HISTORY', '历史+政治+地理', 'POLITICS', 'GEOGRAPHY');

CREATE TABLE exam_year (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_year  SMALLINT NOT NULL,
    province_id     BIGINT NOT NULL,
    name            VARCHAR(100) NOT NULL,
    status          VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_exam_year_province FOREIGN KEY (province_id) REFERENCES province(id),
    CONSTRAINT uq_exam_year_province UNIQUE (admission_year, province_id),
    CONSTRAINT uq_exam_year_id_year UNIQUE (id, admission_year),
    CONSTRAINT ck_exam_year_value CHECK (admission_year BETWEEN 2000 AND 2100),
    CONSTRAINT ck_exam_year_status CHECK (status IN ('DRAFT', 'ACTIVE', 'CLOSED'))
);

CREATE TABLE admission_batch (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_year_id            BIGINT NOT NULL,
    batch_code              VARCHAR(32) NOT NULL,
    name                    VARCHAR(100) NOT NULL,
    max_preferences         SMALLINT NOT NULL DEFAULT 45,
    max_major_preferences   SMALLINT NOT NULL DEFAULT 6,
    application_starts_at   TIMESTAMP,
    application_ends_at     TIMESTAMP,
    status                  VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_admission_batch_exam_year FOREIGN KEY (exam_year_id) REFERENCES exam_year(id),
    CONSTRAINT uq_admission_batch_code UNIQUE (exam_year_id, batch_code),
    CONSTRAINT uq_admission_batch_id_year UNIQUE (id, exam_year_id),
    CONSTRAINT ck_admission_batch_preferences CHECK (max_preferences = 45),
    CONSTRAINT ck_admission_batch_major_preferences CHECK (max_major_preferences = 6),
    CONSTRAINT ck_admission_batch_window CHECK (
        application_starts_at IS NULL OR application_ends_at IS NULL OR application_starts_at < application_ends_at
    ),
    CONSTRAINT ck_admission_batch_status CHECK (status IN ('DRAFT', 'OPEN', 'CLOSED', 'ARCHIVED'))
);

CREATE TABLE candidate (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_year_id        BIGINT NOT NULL,
    exam_number         VARCHAR(10) NOT NULL,
    name                VARCHAR(50) NOT NULL,
    masked_id_card      VARCHAR(32),
    category_code       VARCHAR(16) NOT NULL,
    subject_combination_code VARCHAR(40) NOT NULL,
    status              VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_candidate_exam_year FOREIGN KEY (exam_year_id) REFERENCES exam_year(id),
    CONSTRAINT fk_candidate_category FOREIGN KEY (category_code) REFERENCES subject_category(code),
    CONSTRAINT fk_candidate_subject_combination FOREIGN KEY (subject_combination_code, category_code)
        REFERENCES subject_combination(code, category_code),
    CONSTRAINT uq_candidate_exam_number UNIQUE (exam_year_id, exam_number),
    CONSTRAINT uq_candidate_id_year_category UNIQUE (id, exam_year_id, category_code),
    CONSTRAINT ck_candidate_exam_number CHECK (exam_number ~ '^[0-9]{10}$'),
    CONSTRAINT ck_candidate_status CHECK (status IN ('ACTIVE', 'DISABLED', 'ARCHIVED'))
);

CREATE TABLE candidate_score (
    candidate_id              BIGINT PRIMARY KEY,
    exam_year_id              BIGINT NOT NULL,
    category_code             VARCHAR(16) NOT NULL,
    chinese_score             NUMERIC(5,2) NOT NULL,
    mathematics_score         NUMERIC(5,2) NOT NULL,
    foreign_language_score    NUMERIC(5,2) NOT NULL,
    primary_subject_score     NUMERIC(5,2) NOT NULL,
    secondary_subject_1_score NUMERIC(5,2) NOT NULL,
    secondary_subject_2_score NUMERIC(5,2) NOT NULL,
    policy_bonus              NUMERIC(5,2) NOT NULL DEFAULT 0,
    culture_total             NUMERIC(6,2) NOT NULL,
    final_rank                INTEGER NOT NULL,
    imported_at               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_candidate_score_candidate FOREIGN KEY (candidate_id, exam_year_id, category_code)
        REFERENCES candidate(id, exam_year_id, category_code),
    CONSTRAINT ck_candidate_score_chinese CHECK (chinese_score BETWEEN 0 AND 150),
    CONSTRAINT ck_candidate_score_mathematics CHECK (mathematics_score BETWEEN 0 AND 150),
    CONSTRAINT ck_candidate_score_foreign CHECK (foreign_language_score BETWEEN 0 AND 150),
    CONSTRAINT ck_candidate_score_primary CHECK (primary_subject_score BETWEEN 0 AND 100),
    CONSTRAINT ck_candidate_score_secondary_1 CHECK (secondary_subject_1_score BETWEEN 0 AND 100),
    CONSTRAINT ck_candidate_score_secondary_2 CHECK (secondary_subject_2_score BETWEEN 0 AND 100),
    CONSTRAINT ck_candidate_score_bonus CHECK (policy_bonus >= 0),
    CONSTRAINT ck_candidate_score_total CHECK (culture_total BETWEEN 0 AND 750),
    CONSTRAINT ck_candidate_score_rank CHECK (final_rank > 0)
);

CREATE TABLE institution (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(20) NOT NULL UNIQUE,
    name        VARCHAR(120) NOT NULL,
    province_id BIGINT NOT NULL,
    status      VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_institution_province FOREIGN KEY (province_id) REFERENCES province(id),
    CONSTRAINT ck_institution_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE institution_group (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_year_id    BIGINT NOT NULL,
    institution_id  BIGINT NOT NULL,
    group_code      VARCHAR(32) NOT NULL,
    name            VARCHAR(160) NOT NULL,
    category_code   VARCHAR(16) NOT NULL,
    description     VARCHAR(500),
    status          VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_institution_group_year FOREIGN KEY (exam_year_id) REFERENCES exam_year(id),
    CONSTRAINT fk_institution_group_institution FOREIGN KEY (institution_id) REFERENCES institution(id),
    CONSTRAINT fk_institution_group_category FOREIGN KEY (category_code) REFERENCES subject_category(code),
    CONSTRAINT uq_institution_group_code UNIQUE (exam_year_id, institution_id, group_code),
    CONSTRAINT uq_institution_group_id_year_category UNIQUE (id, exam_year_id, category_code),
    CONSTRAINT ck_institution_group_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE institution_group_subject_requirement (
    institution_group_id BIGINT NOT NULL,
    subject_code         VARCHAR(16) NOT NULL,
    PRIMARY KEY (institution_group_id, subject_code),
    CONSTRAINT fk_group_requirement_group FOREIGN KEY (institution_group_id)
        REFERENCES institution_group(id) ON DELETE CASCADE,
    CONSTRAINT ck_group_requirement_subject CHECK (subject_code IN ('CHEMISTRY', 'BIOLOGY', 'POLITICS', 'GEOGRAPHY'))
);

CREATE TABLE institution_group_major (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_group_id BIGINT NOT NULL,
    major_code           VARCHAR(32) NOT NULL,
    name                 VARCHAR(120) NOT NULL,
    description          VARCHAR(500),
    display_order        SMALLINT NOT NULL DEFAULT 1,
    status               VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_group_major_group FOREIGN KEY (institution_group_id)
        REFERENCES institution_group(id) ON DELETE CASCADE,
    CONSTRAINT uq_group_major_code UNIQUE (institution_group_id, major_code),
    CONSTRAINT uq_group_major_id_group UNIQUE (id, institution_group_id),
    CONSTRAINT uq_group_major_order UNIQUE (institution_group_id, display_order),
    CONSTRAINT ck_group_major_order CHECK (display_order > 0),
    CONSTRAINT ck_group_major_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE enrollment_plan (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_batch_id   BIGINT NOT NULL,
    exam_year_id         BIGINT NOT NULL,
    category_code        VARCHAR(16) NOT NULL,
    institution_group_id BIGINT NOT NULL,
    planned_count        INTEGER NOT NULL,
    filing_ratio         NUMERIC(5,4) NOT NULL DEFAULT 1.0000,
    created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_enrollment_plan_batch FOREIGN KEY (admission_batch_id, exam_year_id)
        REFERENCES admission_batch(id, exam_year_id),
    CONSTRAINT fk_enrollment_plan_group FOREIGN KEY (institution_group_id, exam_year_id, category_code)
        REFERENCES institution_group(id, exam_year_id, category_code),
    CONSTRAINT uq_enrollment_plan_batch_group UNIQUE (admission_batch_id, institution_group_id),
    CONSTRAINT uq_enrollment_plan_identity UNIQUE (
        id, admission_batch_id, exam_year_id, category_code, institution_group_id
    ),
    CONSTRAINT ck_enrollment_plan_count CHECK (planned_count > 0),
    CONSTRAINT ck_enrollment_plan_ratio CHECK (filing_ratio BETWEEN 1.0000 AND 1.0500)
);

CREATE TABLE admission_control_line (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_batch_id  BIGINT NOT NULL,
    exam_year_id        BIGINT NOT NULL,
    category_code       VARCHAR(16) NOT NULL,
    score               NUMERIC(6,2) NOT NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_control_line_batch FOREIGN KEY (admission_batch_id, exam_year_id)
        REFERENCES admission_batch(id, exam_year_id),
    CONSTRAINT fk_control_line_category FOREIGN KEY (category_code) REFERENCES subject_category(code),
    CONSTRAINT uq_control_line_batch_category UNIQUE (admission_batch_id, category_code),
    CONSTRAINT ck_control_line_score CHECK (score BETWEEN 0 AND 750)
);

CREATE TABLE volunteer_draft (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id        BIGINT NOT NULL,
    admission_batch_id  BIGINT NOT NULL,
    exam_year_id        BIGINT NOT NULL,
    category_code       VARCHAR(16) NOT NULL,
    revision            INTEGER NOT NULL DEFAULT 1,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_volunteer_draft_candidate FOREIGN KEY (candidate_id, exam_year_id, category_code)
        REFERENCES candidate(id, exam_year_id, category_code),
    CONSTRAINT fk_volunteer_draft_batch FOREIGN KEY (admission_batch_id, exam_year_id)
        REFERENCES admission_batch(id, exam_year_id),
    CONSTRAINT uq_volunteer_draft_candidate_batch UNIQUE (candidate_id, admission_batch_id),
    CONSTRAINT uq_volunteer_draft_identity UNIQUE (id, admission_batch_id, exam_year_id, category_code),
    CONSTRAINT ck_volunteer_draft_revision CHECK (revision > 0)
);

CREATE TABLE volunteer_draft_item (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    volunteer_draft_id   BIGINT NOT NULL,
    admission_batch_id   BIGINT NOT NULL,
    exam_year_id         BIGINT NOT NULL,
    category_code        VARCHAR(16) NOT NULL,
    enrollment_plan_id   BIGINT NOT NULL,
    institution_group_id BIGINT NOT NULL,
    preference_no        SMALLINT NOT NULL,
    accept_adjustment    BOOLEAN NOT NULL DEFAULT FALSE,
    subject_eligible     BOOLEAN NOT NULL,
    warning_message      VARCHAR(500),
    CONSTRAINT fk_draft_item_draft FOREIGN KEY (
        volunteer_draft_id, admission_batch_id, exam_year_id, category_code
    ) REFERENCES volunteer_draft(id, admission_batch_id, exam_year_id, category_code) ON DELETE CASCADE,
    CONSTRAINT fk_draft_item_plan FOREIGN KEY (
        enrollment_plan_id, admission_batch_id, exam_year_id, category_code, institution_group_id
    ) REFERENCES enrollment_plan(id, admission_batch_id, exam_year_id, category_code, institution_group_id),
    CONSTRAINT uq_draft_item_preference UNIQUE (volunteer_draft_id, preference_no),
    CONSTRAINT uq_draft_item_group UNIQUE (volunteer_draft_id, institution_group_id),
    CONSTRAINT uq_draft_item_id_group UNIQUE (id, institution_group_id),
    CONSTRAINT ck_draft_item_preference CHECK (preference_no BETWEEN 1 AND 45),
    CONSTRAINT ck_draft_item_warning CHECK (subject_eligible OR warning_message IS NOT NULL)
);

CREATE TABLE volunteer_draft_major (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    volunteer_draft_item_id  BIGINT NOT NULL,
    institution_group_id     BIGINT NOT NULL,
    group_major_id           BIGINT NOT NULL,
    preference_no            SMALLINT NOT NULL,
    warning_message          VARCHAR(500),
    CONSTRAINT fk_draft_major_item FOREIGN KEY (volunteer_draft_item_id, institution_group_id)
        REFERENCES volunteer_draft_item(id, institution_group_id) ON DELETE CASCADE,
    CONSTRAINT fk_draft_major_major FOREIGN KEY (group_major_id, institution_group_id)
        REFERENCES institution_group_major(id, institution_group_id),
    CONSTRAINT uq_draft_major_preference UNIQUE (volunteer_draft_item_id, preference_no),
    CONSTRAINT uq_draft_major_choice UNIQUE (volunteer_draft_item_id, group_major_id),
    CONSTRAINT ck_draft_major_preference CHECK (preference_no BETWEEN 1 AND 6)
);

CREATE TABLE volunteer_submission (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id        BIGINT NOT NULL,
    admission_batch_id  BIGINT NOT NULL,
    exam_year_id        BIGINT NOT NULL,
    category_code       VARCHAR(16) NOT NULL,
    version_no          INTEGER NOT NULL,
    submitted_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_volunteer_submission_candidate FOREIGN KEY (candidate_id, exam_year_id, category_code)
        REFERENCES candidate(id, exam_year_id, category_code),
    CONSTRAINT fk_volunteer_submission_batch FOREIGN KEY (admission_batch_id, exam_year_id)
        REFERENCES admission_batch(id, exam_year_id),
    CONSTRAINT uq_volunteer_submission_version UNIQUE (candidate_id, admission_batch_id, version_no),
    CONSTRAINT uq_volunteer_submission_identity UNIQUE (id, admission_batch_id, exam_year_id, category_code),
    CONSTRAINT ck_volunteer_submission_version CHECK (version_no > 0)
);

CREATE TABLE volunteer_submission_item (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    volunteer_submission_id BIGINT NOT NULL,
    admission_batch_id      BIGINT NOT NULL,
    exam_year_id            BIGINT NOT NULL,
    category_code           VARCHAR(16) NOT NULL,
    enrollment_plan_id      BIGINT NOT NULL,
    institution_group_id    BIGINT NOT NULL,
    preference_no           SMALLINT NOT NULL,
    accept_adjustment       BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_submission_item_submission FOREIGN KEY (
        volunteer_submission_id, admission_batch_id, exam_year_id, category_code
    ) REFERENCES volunteer_submission(id, admission_batch_id, exam_year_id, category_code),
    CONSTRAINT fk_submission_item_plan FOREIGN KEY (
        enrollment_plan_id, admission_batch_id, exam_year_id, category_code, institution_group_id
    ) REFERENCES enrollment_plan(id, admission_batch_id, exam_year_id, category_code, institution_group_id),
    CONSTRAINT uq_submission_item_preference UNIQUE (volunteer_submission_id, preference_no),
    CONSTRAINT uq_submission_item_group UNIQUE (volunteer_submission_id, institution_group_id),
    CONSTRAINT uq_submission_item_id_group UNIQUE (id, institution_group_id),
    CONSTRAINT ck_submission_item_preference CHECK (preference_no BETWEEN 1 AND 45)
);

CREATE TABLE volunteer_submission_major (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    volunteer_submission_item_id  BIGINT NOT NULL,
    institution_group_id          BIGINT NOT NULL,
    group_major_id                BIGINT NOT NULL,
    preference_no                 SMALLINT NOT NULL,
    warning_message               VARCHAR(500),
    CONSTRAINT fk_submission_major_item FOREIGN KEY (volunteer_submission_item_id, institution_group_id)
        REFERENCES volunteer_submission_item(id, institution_group_id),
    CONSTRAINT fk_submission_major_major FOREIGN KEY (group_major_id, institution_group_id)
        REFERENCES institution_group_major(id, institution_group_id),
    CONSTRAINT uq_submission_major_preference UNIQUE (volunteer_submission_item_id, preference_no),
    CONSTRAINT uq_submission_major_choice UNIQUE (volunteer_submission_item_id, group_major_id),
    CONSTRAINT ck_submission_major_preference CHECK (preference_no BETWEEN 1 AND 6)
);

CREATE TABLE admission_run (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_batch_id  BIGINT NOT NULL,
    exam_year_id        BIGINT NOT NULL,
    run_no              INTEGER NOT NULL,
    status              VARCHAR(16) NOT NULL DEFAULT 'CREATED',
    operator_user_id    BIGINT NOT NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at          TIMESTAMP,
    completed_at        TIMESTAMP,
    failure_reason      VARCHAR(1000),
    CONSTRAINT fk_admission_run_batch FOREIGN KEY (admission_batch_id, exam_year_id)
        REFERENCES admission_batch(id, exam_year_id),
    CONSTRAINT fk_admission_run_operator FOREIGN KEY (operator_user_id) REFERENCES sys_user(id),
    CONSTRAINT uq_admission_run_version UNIQUE (admission_batch_id, run_no),
    CONSTRAINT uq_admission_run_id_batch UNIQUE (id, admission_batch_id),
    CONSTRAINT ck_admission_run_no CHECK (run_no > 0),
    CONSTRAINT ck_admission_run_status CHECK (status IN ('CREATED', 'RUNNING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_admission_run_timestamps CHECK (
        completed_at IS NULL OR (started_at IS NOT NULL AND completed_at >= started_at)
    )
);

CREATE TABLE admission_control_line_snapshot (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                  BIGINT NOT NULL,
    source_control_line_id  BIGINT NOT NULL,
    category_code           VARCHAR(16) NOT NULL,
    score                   NUMERIC(6,2) NOT NULL,
    CONSTRAINT fk_control_snapshot_run FOREIGN KEY (run_id) REFERENCES admission_run(id),
    CONSTRAINT fk_control_snapshot_source FOREIGN KEY (source_control_line_id) REFERENCES admission_control_line(id),
    CONSTRAINT fk_control_snapshot_category FOREIGN KEY (category_code) REFERENCES subject_category(code),
    CONSTRAINT uq_control_snapshot_category UNIQUE (run_id, category_code),
    CONSTRAINT ck_control_snapshot_score CHECK (score BETWEEN 0 AND 750)
);

CREATE TABLE admission_candidate_snapshot (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                      BIGINT NOT NULL,
    source_candidate_id         BIGINT NOT NULL,
    source_submission_id        BIGINT NOT NULL,
    exam_number                 VARCHAR(10) NOT NULL,
    name                        VARCHAR(50) NOT NULL,
    category_code               VARCHAR(16) NOT NULL,
    secondary_subject_1         VARCHAR(16) NOT NULL,
    secondary_subject_2         VARCHAR(16) NOT NULL,
    chinese_score               NUMERIC(5,2) NOT NULL,
    mathematics_score           NUMERIC(5,2) NOT NULL,
    foreign_language_score      NUMERIC(5,2) NOT NULL,
    primary_subject_score       NUMERIC(5,2) NOT NULL,
    secondary_subject_1_score   NUMERIC(5,2) NOT NULL,
    secondary_subject_2_score   NUMERIC(5,2) NOT NULL,
    policy_bonus                NUMERIC(5,2) NOT NULL,
    culture_total               NUMERIC(6,2) NOT NULL,
    final_rank                  INTEGER NOT NULL,
    effective_submission_version INTEGER NOT NULL,
    sort_order                  BIGINT,
    CONSTRAINT fk_candidate_snapshot_run FOREIGN KEY (run_id) REFERENCES admission_run(id),
    CONSTRAINT fk_candidate_snapshot_source FOREIGN KEY (source_candidate_id) REFERENCES candidate(id),
    CONSTRAINT fk_candidate_snapshot_submission FOREIGN KEY (source_submission_id) REFERENCES volunteer_submission(id),
    CONSTRAINT fk_candidate_snapshot_category FOREIGN KEY (category_code) REFERENCES subject_category(code),
    CONSTRAINT uq_candidate_snapshot_candidate UNIQUE (run_id, source_candidate_id),
    CONSTRAINT uq_candidate_snapshot_submission UNIQUE (run_id, source_submission_id),
    CONSTRAINT uq_candidate_snapshot_id_run UNIQUE (id, run_id),
    CONSTRAINT ck_candidate_snapshot_version CHECK (effective_submission_version > 0),
    CONSTRAINT ck_candidate_snapshot_rank CHECK (final_rank > 0),
    CONSTRAINT ck_candidate_snapshot_sort_order CHECK (sort_order IS NULL OR sort_order > 0)
);

CREATE TABLE admission_plan_snapshot (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                  BIGINT NOT NULL,
    source_plan_id          BIGINT NOT NULL,
    category_code           VARCHAR(16) NOT NULL,
    institution_code        VARCHAR(20) NOT NULL,
    institution_name        VARCHAR(120) NOT NULL,
    group_code              VARCHAR(32) NOT NULL,
    group_name              VARCHAR(160) NOT NULL,
    required_subjects       VARCHAR(100) NOT NULL DEFAULT '',
    planned_count           INTEGER NOT NULL,
    filing_ratio            NUMERIC(5,4) NOT NULL,
    filing_capacity         INTEGER NOT NULL,
    CONSTRAINT fk_plan_snapshot_run FOREIGN KEY (run_id) REFERENCES admission_run(id),
    CONSTRAINT fk_plan_snapshot_source FOREIGN KEY (source_plan_id) REFERENCES enrollment_plan(id),
    CONSTRAINT fk_plan_snapshot_category FOREIGN KEY (category_code) REFERENCES subject_category(code),
    CONSTRAINT uq_plan_snapshot_plan UNIQUE (run_id, source_plan_id),
    CONSTRAINT uq_plan_snapshot_id_run UNIQUE (id, run_id),
    CONSTRAINT ck_plan_snapshot_count CHECK (planned_count > 0),
    CONSTRAINT ck_plan_snapshot_ratio CHECK (filing_ratio BETWEEN 1.0000 AND 1.0500),
    CONSTRAINT ck_plan_snapshot_capacity CHECK (filing_capacity >= planned_count)
);

CREATE TABLE admission_preference_snapshot (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                      BIGINT NOT NULL,
    candidate_snapshot_id       BIGINT NOT NULL,
    plan_snapshot_id            BIGINT NOT NULL,
    source_submission_item_id   BIGINT NOT NULL,
    preference_no               SMALLINT NOT NULL,
    accept_adjustment           BOOLEAN NOT NULL,
    eligible                    BOOLEAN NOT NULL,
    invalid_reason              VARCHAR(500),
    CONSTRAINT fk_preference_snapshot_run FOREIGN KEY (run_id) REFERENCES admission_run(id),
    CONSTRAINT fk_preference_snapshot_candidate FOREIGN KEY (candidate_snapshot_id, run_id)
        REFERENCES admission_candidate_snapshot(id, run_id),
    CONSTRAINT fk_preference_snapshot_plan FOREIGN KEY (plan_snapshot_id, run_id)
        REFERENCES admission_plan_snapshot(id, run_id),
    CONSTRAINT fk_preference_snapshot_source FOREIGN KEY (source_submission_item_id)
        REFERENCES volunteer_submission_item(id),
    CONSTRAINT uq_preference_snapshot_order UNIQUE (run_id, candidate_snapshot_id, preference_no),
    CONSTRAINT uq_preference_snapshot_plan UNIQUE (run_id, candidate_snapshot_id, plan_snapshot_id),
    CONSTRAINT uq_preference_snapshot_id_run UNIQUE (id, run_id),
    CONSTRAINT ck_preference_snapshot_order CHECK (preference_no BETWEEN 1 AND 45),
    CONSTRAINT ck_preference_snapshot_reason CHECK (eligible OR invalid_reason IS NOT NULL)
);

CREATE TABLE admission_preference_major_snapshot (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                          BIGINT NOT NULL,
    preference_snapshot_id          BIGINT NOT NULL,
    source_submission_major_id      BIGINT NOT NULL,
    preference_no                   SMALLINT NOT NULL,
    major_code                      VARCHAR(32) NOT NULL,
    major_name                      VARCHAR(120) NOT NULL,
    warning_message                 VARCHAR(500),
    CONSTRAINT fk_preference_major_snapshot_run FOREIGN KEY (run_id) REFERENCES admission_run(id),
    CONSTRAINT fk_preference_major_snapshot_preference FOREIGN KEY (preference_snapshot_id, run_id)
        REFERENCES admission_preference_snapshot(id, run_id),
    CONSTRAINT fk_preference_major_snapshot_source FOREIGN KEY (source_submission_major_id)
        REFERENCES volunteer_submission_major(id),
    CONSTRAINT uq_preference_major_snapshot_order UNIQUE (preference_snapshot_id, preference_no),
    CONSTRAINT ck_preference_major_snapshot_order CHECK (preference_no BETWEEN 1 AND 6)
);

CREATE TABLE admission_search_trace (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                  BIGINT NOT NULL,
    candidate_snapshot_id   BIGINT NOT NULL,
    plan_snapshot_id        BIGINT,
    preference_no           SMALLINT,
    sequence_no             SMALLINT NOT NULL,
    action                  VARCHAR(32) NOT NULL,
    detail                  VARCHAR(1000),
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_search_trace_run FOREIGN KEY (run_id) REFERENCES admission_run(id),
    CONSTRAINT fk_search_trace_candidate FOREIGN KEY (candidate_snapshot_id, run_id)
        REFERENCES admission_candidate_snapshot(id, run_id),
    CONSTRAINT fk_search_trace_plan FOREIGN KEY (plan_snapshot_id, run_id)
        REFERENCES admission_plan_snapshot(id, run_id),
    CONSTRAINT uq_search_trace_sequence UNIQUE (run_id, candidate_snapshot_id, sequence_no),
    CONSTRAINT ck_search_trace_preference CHECK (preference_no IS NULL OR preference_no BETWEEN 1 AND 45),
    CONSTRAINT ck_search_trace_sequence CHECK (sequence_no > 0),
    CONSTRAINT ck_search_trace_action CHECK (action IN (
        'BELOW_CONTROL_LINE', 'NO_VALID_PREFERENCE', 'CHECKED', 'SKIPPED', 'FILED', 'QUOTA_FULL'
    ))
);

CREATE TABLE admission_result_snapshot (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                  BIGINT NOT NULL,
    candidate_snapshot_id   BIGINT NOT NULL,
    plan_snapshot_id        BIGINT,
    status                  VARCHAR(32) NOT NULL,
    matched_preference_no   SMALLINT,
    reason                  VARCHAR(1000),
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_result_snapshot_run FOREIGN KEY (run_id) REFERENCES admission_run(id),
    CONSTRAINT fk_result_snapshot_candidate FOREIGN KEY (candidate_snapshot_id, run_id)
        REFERENCES admission_candidate_snapshot(id, run_id),
    CONSTRAINT fk_result_snapshot_plan FOREIGN KEY (plan_snapshot_id, run_id)
        REFERENCES admission_plan_snapshot(id, run_id),
    CONSTRAINT uq_result_snapshot_candidate UNIQUE (run_id, candidate_snapshot_id),
    CONSTRAINT ck_result_snapshot_status CHECK (status IN (
        'FILED', 'SLIPPED', 'BELOW_CONTROL_LINE', 'NO_VALID_PREFERENCE'
    )),
    CONSTRAINT ck_result_snapshot_preference CHECK (
        matched_preference_no IS NULL OR matched_preference_no BETWEEN 1 AND 45
    ),
    CONSTRAINT ck_result_snapshot_filed CHECK (
        (status = 'FILED' AND plan_snapshot_id IS NOT NULL AND matched_preference_no IS NOT NULL)
        OR (status <> 'FILED' AND plan_snapshot_id IS NULL AND matched_preference_no IS NULL)
    )
);

CREATE FUNCTION reject_immutable_change() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION '% rows are immutable', TG_TABLE_NAME USING ERRCODE = '55000';
END;
$$ LANGUAGE plpgsql;

CREATE FUNCTION protect_admission_snapshot() RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION '% rows are immutable', TG_TABLE_NAME USING ERRCODE = '55000';
    END IF;
    IF EXISTS (SELECT 1 FROM admission_run WHERE id = NEW.run_id AND status IN ('COMPLETED', 'FAILED')) THEN
        RAISE EXCEPTION 'admission run % is closed', NEW.run_id USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE FUNCTION protect_closed_admission_run() RETURNS TRIGGER AS $$
BEGIN
    IF OLD.status IN ('COMPLETED', 'FAILED') THEN
        RAISE EXCEPTION 'closed admission run % is immutable', OLD.id USING ERRCODE = '55000';
    END IF;
    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_volunteer_submission_immutable
    BEFORE UPDATE OR DELETE ON volunteer_submission
    FOR EACH ROW EXECUTE FUNCTION reject_immutable_change();
CREATE TRIGGER trg_volunteer_submission_item_immutable
    BEFORE UPDATE OR DELETE ON volunteer_submission_item
    FOR EACH ROW EXECUTE FUNCTION reject_immutable_change();
CREATE TRIGGER trg_volunteer_submission_major_immutable
    BEFORE UPDATE OR DELETE ON volunteer_submission_major
    FOR EACH ROW EXECUTE FUNCTION reject_immutable_change();
CREATE TRIGGER trg_admission_run_closed
    BEFORE UPDATE OR DELETE ON admission_run
    FOR EACH ROW EXECUTE FUNCTION protect_closed_admission_run();

CREATE TRIGGER trg_control_line_snapshot_immutable
    BEFORE INSERT OR UPDATE OR DELETE ON admission_control_line_snapshot
    FOR EACH ROW EXECUTE FUNCTION protect_admission_snapshot();
CREATE TRIGGER trg_candidate_snapshot_immutable
    BEFORE INSERT OR UPDATE OR DELETE ON admission_candidate_snapshot
    FOR EACH ROW EXECUTE FUNCTION protect_admission_snapshot();
CREATE TRIGGER trg_plan_snapshot_immutable
    BEFORE INSERT OR UPDATE OR DELETE ON admission_plan_snapshot
    FOR EACH ROW EXECUTE FUNCTION protect_admission_snapshot();
CREATE TRIGGER trg_preference_snapshot_immutable
    BEFORE INSERT OR UPDATE OR DELETE ON admission_preference_snapshot
    FOR EACH ROW EXECUTE FUNCTION protect_admission_snapshot();
CREATE TRIGGER trg_preference_major_snapshot_immutable
    BEFORE INSERT OR UPDATE OR DELETE ON admission_preference_major_snapshot
    FOR EACH ROW EXECUTE FUNCTION protect_admission_snapshot();
CREATE TRIGGER trg_search_trace_immutable
    BEFORE INSERT OR UPDATE OR DELETE ON admission_search_trace
    FOR EACH ROW EXECUTE FUNCTION protect_admission_snapshot();
CREATE TRIGGER trg_result_snapshot_immutable
    BEFORE INSERT OR UPDATE OR DELETE ON admission_result_snapshot
    FOR EACH ROW EXECUTE FUNCTION protect_admission_snapshot();

CREATE INDEX idx_candidate_year_category_rank ON candidate(exam_year_id, category_code, id);
CREATE INDEX idx_candidate_score_queue ON candidate_score(exam_year_id, category_code, final_rank, candidate_id);
CREATE INDEX idx_group_year_category ON institution_group(exam_year_id, category_code, institution_id);
CREATE INDEX idx_group_requirement_group ON institution_group_subject_requirement(institution_group_id);
CREATE INDEX idx_group_major_group ON institution_group_major(institution_group_id, display_order);
CREATE INDEX idx_enrollment_plan_batch_category ON enrollment_plan(admission_batch_id, category_code, institution_group_id);
CREATE INDEX idx_control_line_batch ON admission_control_line(admission_batch_id, category_code);
CREATE INDEX idx_draft_candidate_batch ON volunteer_draft(candidate_id, admission_batch_id);
CREATE INDEX idx_draft_item_order ON volunteer_draft_item(volunteer_draft_id, preference_no);
CREATE INDEX idx_submission_candidate_latest ON volunteer_submission(candidate_id, admission_batch_id, version_no DESC);
CREATE INDEX idx_submission_item_order ON volunteer_submission_item(volunteer_submission_id, preference_no);
CREATE INDEX idx_admission_run_batch_version ON admission_run(admission_batch_id, run_no DESC);
CREATE INDEX idx_candidate_snapshot_queue ON admission_candidate_snapshot(run_id, category_code, sort_order, final_rank);
CREATE INDEX idx_plan_snapshot_group ON admission_plan_snapshot(run_id, category_code, institution_code, group_code);
CREATE INDEX idx_preference_snapshot_candidate ON admission_preference_snapshot(run_id, candidate_snapshot_id, preference_no);
CREATE INDEX idx_search_trace_candidate ON admission_search_trace(run_id, candidate_snapshot_id, sequence_no);
CREATE INDEX idx_result_snapshot_status ON admission_result_snapshot(run_id, status, candidate_snapshot_id);
