ALTER TABLE admission_batch ADD COLUMN config_revision INTEGER NOT NULL DEFAULT 0;
ALTER TABLE candidate ADD COLUMN data_origin VARCHAR(16) NOT NULL DEFAULT 'PRODUCTION'
    CHECK (data_origin IN ('DEMO', 'PRODUCTION'));
ALTER TABLE volunteer_submission ADD COLUMN request_id UUID;
ALTER TABLE volunteer_submission ADD COLUMN draft_revision INTEGER;
ALTER TABLE volunteer_submission ADD CONSTRAINT uq_submission_request UNIQUE(candidate_id, admission_batch_id, request_id);
ALTER TABLE auth_session ADD COLUMN last_seen_at TIMESTAMPTZ;

CREATE TABLE candidate_notice_acceptance (
    candidate_id BIGINT NOT NULL REFERENCES candidate(id) ON DELETE CASCADE,
    notice_version VARCHAR(32) NOT NULL,
    accepted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(candidate_id, notice_version)
);
CREATE TABLE workflow_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_user_id BIGINT NOT NULL REFERENCES sys_user(id),
    action VARCHAR(40) NOT NULL,
    target_id BIGINT,
    before_json JSONB NOT NULL,
    after_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER trg_workflow_audit_immutable BEFORE UPDATE OR DELETE ON workflow_audit
    FOR EACH ROW EXECUTE FUNCTION reject_immutable_change();

CREATE FUNCTION protect_candidate_origin() RETURNS TRIGGER AS $$
BEGIN
    IF OLD.data_origin <> NEW.data_origin THEN
        RAISE EXCEPTION 'candidate origin is immutable' USING ERRCODE='55000';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_candidate_origin BEFORE UPDATE ON candidate
    FOR EACH ROW EXECUTE FUNCTION protect_candidate_origin();

-- Reset permits DELETE only for the transaction's explicitly selected demo IDs.
CREATE FUNCTION demo_reset_allows(table_name TEXT, row_data JSONB) RETURNS BOOLEAN AS $$
DECLARE
    ids BIGINT[];
    target BIGINT;
BEGIN
    IF table_name IN ('volunteer_submission', 'volunteer_submission_item', 'volunteer_submission_major') THEN
        ids := string_to_array(current_setting('gaokao.reset_candidates', TRUE), ',')::BIGINT[];
        IF table_name = 'volunteer_submission' THEN target := (row_data->>'candidate_id')::BIGINT;
        ELSIF table_name = 'volunteer_submission_item' THEN
            SELECT candidate_id INTO target FROM volunteer_submission WHERE id=(row_data->>'volunteer_submission_id')::BIGINT;
        ELSE
            SELECT s.candidate_id INTO target FROM volunteer_submission s JOIN volunteer_submission_item i ON i.volunteer_submission_id=s.id
                WHERE i.id=(row_data->>'volunteer_submission_item_id')::BIGINT;
        END IF;
        RETURN COALESCE(target=ANY(ids), FALSE) AND EXISTS(SELECT 1 FROM candidate WHERE id=target AND data_origin='DEMO');
    END IF;
    ids := string_to_array(current_setting('gaokao.reset_runs', TRUE), ',')::BIGINT[];
    target := CASE WHEN table_name='admission_run' THEN (row_data->>'id')::BIGINT ELSE (row_data->>'run_id')::BIGINT END;
    RETURN COALESCE(target=ANY(ids), FALSE);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION reject_immutable_change() RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP='DELETE' AND TG_TABLE_NAME IN ('volunteer_submission','volunteer_submission_item','volunteer_submission_major')
        AND demo_reset_allows(TG_TABLE_NAME, to_jsonb(OLD)) THEN RETURN OLD; END IF;
    RAISE EXCEPTION '% rows are immutable', TG_TABLE_NAME USING ERRCODE = '55000';
END;
$$ LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION protect_admission_snapshot() RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP='DELETE' AND demo_reset_allows(TG_TABLE_NAME, to_jsonb(OLD)) THEN RETURN OLD; END IF;
    IF TG_OP <> 'INSERT' THEN RAISE EXCEPTION '% rows are immutable', TG_TABLE_NAME USING ERRCODE='55000'; END IF;
    IF EXISTS(SELECT 1 FROM admission_run WHERE id=NEW.run_id AND status IN ('COMPLETED','FAILED')) THEN
        RAISE EXCEPTION 'admission run % is closed', NEW.run_id USING ERRCODE='55000';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION protect_closed_admission_run() RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP='DELETE' AND demo_reset_allows(TG_TABLE_NAME, to_jsonb(OLD)) THEN RETURN OLD; END IF;
    IF OLD.status IN ('COMPLETED','FAILED') THEN
        RAISE EXCEPTION 'closed admission run % is immutable', OLD.id USING ERRCODE='55000';
    END IF;
    RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END;
END;
$$ LANGUAGE plpgsql;
